services:
  php80:
    build: docker/php80
    volumes:
      - ./:/var/www
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - mysql
    networks:
      - app-network

  php83:
    build: docker/php83
    volumes:
      - ./:/var/www
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    build: ./docker/mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      TZ: 'Asia/Tokyo'
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    links:
      - mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
